### ISSUE TITLE
题外话！

### ISSUE THREAD

**Issue by poembro** [zhangxinhang/Soul#1]
看到你的 zxh 项目 [zxh](https://github.com/zhangxinhang/zxh/blob/e68bb22c8378e4e9fb4467f1172b02a84b1c0cab/source/_posts/technology/2015-11-24-websocket-redis-openresty.md)  这个文件描述

提到
```
1. 需要为每个连接建立redis 频道，redis 对小于10000的频道数支持较好。数量多了涉及redis的集群部署
> 我现在也在采用这个方案。 可否交流一下  找不到你的联系方式

2.连接断开是会自动退出redis连接，sub 通道断开。
>连接断开可以加入  cosocket 比如set_keepalive     
>但是用户一但断开不知道你有问没有执行  rds:unsubscribe(session_id) 或者 rds:del(session_id) 
```

**Comment by zhangxinhang** [comment]
这个过去时间有点长了，有些细节记不清了。具体在项目中也没有大规模使用。仅仅是个技术研究。

关于10000数字的来历，有点模糊了，忘了从那个技术文章中了解到的。这里的10000是单个redis支撑的数据。

订阅通道在wb关闭后，退出循环，单独的线程也结束了。线程中的redis连接关闭，通道也就关了。

**Comment by poembro** [comment]
非常感谢你的回复!

也就是说 redis的连接一旦断开，会自动关闭那条发布与订阅的通道，
不需要手动去rds:unsubscribe(session_id) 或者 rds:del(session_id) 


从过往的实际案例上来说，单机c10k就还好。 不行再堆机器

**Comment by zhangxinhang** [comment]
不客气。
是的，不需要手动去关闭。
嗯，先优化，充分榨取机器的价值。
